# Generated by Django 5.1 on 2026-03-01 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_amenity'),
        ('tenants', '0002_tenant_city'),
        ('users', '0003_otpcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500)),
                ('is_cover', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'property_images',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PropertyNearbyPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('place_type', models.CharField(blank=True, max_length=100, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'property_nearby_places',
                'ordering': ['distance_km'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('listing_type', models.CharField(choices=[('sale', 'Sale'), ('pending_listing', 'Pending Listing')], max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('property_type', models.CharField(choices=[('house', 'Casa'), ('apartment', 'Departamento'), ('land', 'Terreno'), ('commercial', 'Comercial'), ('office', 'Oficina'), ('warehouse', 'Bodega'), ('other', 'Otro')], max_length=20)),
                ('property_condition', models.CharField(blank=True, choices=[('new', 'Nueva'), ('semi_new', 'Semi-nueva'), ('used', 'Usada')], max_length=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='MXN', max_length=10)),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('parking_spaces', models.IntegerField(default=0)),
                ('construction_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('land_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('views', models.IntegerField(default=0)),
                ('address_street', models.CharField(blank=True, max_length=255, null=True)),
                ('address_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address_neighborhood', models.CharField(blank=True, max_length=255, null=True)),
                ('address_zip', models.CharField(blank=True, max_length=20, null=True)),
                ('zone', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('video_id', models.CharField(blank=True, max_length=50, null=True)),
                ('video_thumbnail', models.CharField(blank=True, max_length=500, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='locations.city')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'db_table': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_amenities', to='locations.amenity')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_amenities', to='properties.property')),
            ],
            options={
                'db_table': 'property_amenities',
            },
        ),
        migrations.CreateModel(
            name='PropertyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('agent_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_assignments', to='users.tenantmembership')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='properties.property')),
            ],
            options={
                'db_table': 'property_assignments',
            },
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_url', models.CharField(max_length=500)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('document_stage', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.property')),
            ],
            options={
                'db_table': 'property_documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
