# Generated by Django 5.1 on 2026-03-01 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('transactions', '0001_initial'),
        ('users', '0003_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydocument',
            name='purchase_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='transactions.purchaseprocess'),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='uploaded_by_membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to='users.tenantmembership'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property'),
        ),
        migrations.AddField(
            model_name='propertynearbyplace',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_places', to='properties.property'),
        ),
        migrations.AlterUniqueTogether(
            name='propertyamenity',
            unique_together={('property', 'amenity')},
        ),
        migrations.AlterUniqueTogether(
            name='propertyassignment',
            unique_together={('property', 'agent_membership')},
        ),
    ]
