# Generated by Django 5.1 on 2026-03-06 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
        ('tenants', '0002_tenant_city'),
        ('users', '0004_add_client_financial_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_properties', to='users.tenantmembership')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_properties', to='tenants.tenant')),
            ],
            options={
                'db_table': 'saved_properties',
                'ordering': ['-created_at'],
                'unique_together': {('client_membership', 'property')},
            },
        ),
    ]
