# Generated by Django 5.1 on 2026-03-07 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_add_created_by_membership'),
        ('users', '0005_clientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleprocess',
            name='name_form',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='saleprocess',
            name='phone_form',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='saleprocess',
            name='client_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_sale_processes', to='users.tenantmembership'),
        ),
        migrations.AlterField(
            model_name='saleprocess',
            name='status',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('en_revision', 'En revisión'), ('vendedor_completado', 'Vendedor completado'), ('contacto_inicial', 'Contacto inicial'), ('evaluacion', 'Evaluación'), ('valuacion', 'Valuación'), ('firma_contrato', 'Firma de contrato'), ('marketing', 'Marketing'), ('publicar', 'Publicar'), ('cancelado', 'Cancelado')], default='nuevo', max_length=20),
        ),
    ]
