# Generated by Django 5.1 on 2026-03-07 21:38

from django.db import migrations


def migrate_statuses_forward(apps, schema_editor):
    SaleProcess = apps.get_model('transactions', 'SaleProcess')
    mapping = {
        'seller_completed': 'vendedor_completado',
        'presentacion': 'evaluacion',
        'publicacion': 'publicar',
    }
    for old_status, new_status in mapping.items():
        SaleProcess.objects.filter(status=old_status).update(status=new_status)


def migrate_statuses_reverse(apps, schema_editor):
    SaleProcess = apps.get_model('transactions', 'SaleProcess')
    mapping = {
        'vendedor_completado': 'seller_completed',
        'publicar': 'publicacion',
    }
    for old_status, new_status in mapping.items():
        SaleProcess.objects.filter(status=old_status).update(status=new_status)


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_saleprocess_name_form_saleprocess_phone_form_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_statuses_forward, migrate_statuses_reverse),
    ]
