# Generated by Django 5.1 on 2026-03-06 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otpcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('individual', 'Individual'), ('conyugal', 'Conyugal'), ('cofinavit', 'Cofinavit')], max_length=20)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('partner_monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True)),
                ('savings_for_enganche', models.DecimalField(decimal_places=2, max_digits=12)),
                ('has_infonavit', models.BooleanField(default=False)),
                ('infonavit_subcuenta_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True)),
                ('calculated_budget', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_profile', to='users.tenantmembership')),
            ],
            options={
                'verbose_name': 'Client Financial Profile',
                'verbose_name_plural': 'Client Financial Profiles',
                'db_table': 'client_financial_profiles',
            },
        ),
    ]
