# Generated by Django 5.1 on 2026-03-01 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_initial'),
        ('tenants', '0002_tenant_city'),
        ('users', '0003_otpcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('has_lunch_break', models.BooleanField(default=True)),
                ('lunch_start', models.TimeField(blank=True, null=True)),
                ('lunch_end', models.TimeField(blank=True, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='users.tenantmembership')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_schedules', to='tenants.tenant')),
            ],
            options={
                'db_table': 'agent_schedules',
            },
        ),
        migrations.CreateModel(
            name='AgentUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(choices=[('vacation', 'Vacaciones'), ('sick_leave', 'Incapacidad'), ('personal', 'Asunto personal'), ('training', 'Capacitación'), ('other', 'Otro')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailabilities', to='users.tenantmembership')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_unavailabilities', to='tenants.tenant')),
            ],
            options={
                'db_table': 'agent_unavailabilities',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('client_email', models.CharField(blank=True, max_length=255)),
                ('client_phone', models.CharField(blank=True, max_length=50)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('programada', 'Programada'), ('confirmada', 'Confirmada'), ('en_progreso', 'En progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_show', 'No show'), ('reagendada', 'Reagendada')], default='programada', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_appointments', to='users.tenantmembership')),
                ('client_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_appointments', to='users.tenantmembership')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='tenants.tenant')),
            ],
            options={
                'db_table': 'appointments',
            },
        ),
        migrations.CreateModel(
            name='AppointmentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_duration_minutes', models.PositiveIntegerField(default=60)),
                ('max_advance_days', models.PositiveIntegerField(default=30)),
                ('min_advance_hours', models.PositiveIntegerField(default=24)),
                ('day_start_time', models.TimeField(default='09:00')),
                ('day_end_time', models.TimeField(default='18:00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_settings', to='tenants.tenant')),
            ],
            options={
                'db_table': 'appointment_settings',
            },
        ),
        migrations.CreateModel(
            name='ScheduleBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_type', models.CharField(choices=[('lunch', 'Comida'), ('coffee', 'Café'), ('rest', 'Descanso'), ('other', 'Otro')], max_length=10)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='appointments.agentschedule')),
            ],
            options={
                'db_table': 'schedule_breaks',
            },
        ),
    ]
