# Generated by Django 5.1 on 2026-03-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('primera_visita', 'Primera Visita'), ('seguimiento', 'Seguimiento'), ('cierre_contrato', 'Cierre de Contrato'), ('entrega_llaves', 'Entrega de Llaves'), ('avaluo', 'Avalúo')], default='primera_visita', max_length=20),
        ),
    ]
